version: '3.9'
services:
  nginx:
    container_name: smart-blogging-web
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    depends_on:
      - api
  redis:
    container_name: smart-blogging-redis
    image: redis:alpine
  api:
    container_name: smart-blogging-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c "chmod +x /app/scripts/start_script.sh && /app/scripts/start_script.sh"
    volumes:
      - .alembic/versions:/app/migrations
    depends_on:
      - redis
